# -*- coding: utf-8 -*-
"""e commerce analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wrqpm0anX56MeziZXjLldJWkE3dlTyxG
"""

import pandas as pd

df = pd.read_csv('/content/archive.zip')
df

df.head(10)

df.tail(10)

df.dtypes

df.isnull().sum()

len(df.columns)

len(df)

df.info()

df.columns

df['Purchase Price'].max()

df['Purchase Price'].min()

df['Purchase Price'].mean()

df.columns

df['Language']=='fr'

len(df[df['Language']=='fr'])

df[df['Language']=='fr'].count()

df.columns

len(df[df['Job'].str.contains('engineer',case=False)])

df.columns

df[df['IP Address']=="132.207.160.22"]['Email']

len(df[(df['CC Provider']=="MasterCard") & (df['Purchase Price']>50)])

df[(df['CC Provider']=="Mastercard") \
 & (df['Purchase Price']>50)].count()

df[df['Credit Card']==4664825258997302]["Email"]

df['AM or PM'].value_counts()

df['CC Exp Date']

def fun():
    count=0
    for date in df['CC Exp Date']:
        if date.split('/')[1]=='20':
         count=count+1
    print(count)

fun()

len(df[df['CC Exp Date'].apply(lambda x:x [3:]=='20')])

list1=[]
for email in df['Email']:
  list1.append(email.split('@')[1])

df['temp']=list1

df.head(1)

df['temp'].value_counts().head()

df['Email'].apply(lambda x:x.split('@')[1]).value_counts().head()